-- ============================================================
-- Employee ID Format Update: BZ-EMP-XXXX → B-XXXXX
-- New format: B-3231, B-3232, B-3233 ... (incrementing from 3231)
-- Run this in your Supabase SQL Editor.
-- ============================================================

-- Step 1: Advance the sequence safely.
-- We take the maximum numeric suffix from existing employee_id values
-- (both old BZ-EMP-XXXX and any already-migrated B-XXXX records),
-- then set the sequence to max(that value, 3230) so the NEXT call to
-- nextval() returns at least 3231 — without ever going backwards and
-- risking collisions with already-assigned IDs.
DO $$
DECLARE
  v_max bigint;
BEGIN
  SELECT COALESCE(
    MAX(
      CASE
        WHEN employee_id ~ '^BZ-EMP-[0-9]+$'
          THEN split_part(employee_id, '-', 3)::bigint
        WHEN employee_id ~ '^B-[0-9]+$'
          THEN split_part(employee_id, '-', 2)::bigint
        ELSE 0
      END
    ), 0
  )
  INTO v_max
  FROM public.agents;

  -- Ensure we never go below 3230 (so next ID is at least B-3231)
  v_max := GREATEST(v_max, 3230);

  PERFORM setval('public.agent_emp_seq', v_max, true);
END $$;

-- Step 2: Update the trigger function to use the new format
CREATE OR REPLACE FUNCTION public.set_agent_ids()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  IF new.employee_id IS NULL OR new.employee_id = '' THEN
    new.employee_id := 'B-' || nextval('public.agent_emp_seq')::text;
  END IF;
  IF new.reference_id IS NULL OR new.reference_id = '' THEN
    new.reference_id := 'BZ-REF-' || to_char(now(),'YY') || '-' || lpad(nextval('public.agent_ref_seq')::text, 5, '0');
  END IF;
  RETURN new;
END; $$;

-- Step 3: Migrate existing BZ-EMP-XXXX employee IDs to B-XXXX format
-- Collision-safe, idempotent: rows that would conflict with an already-existing
-- B-<n> record get a brand-new sequence value instead of the original number.
--
-- Pre-check (run before applying to review any potential conflicts):
--   SELECT a.id, a.employee_id AS old_id, 'B-' || split_part(a.employee_id,'-',3) AS new_id
--   FROM public.agents a
--   WHERE a.employee_id LIKE 'BZ-EMP-%'
--     AND EXISTS (
--       SELECT 1 FROM public.agents b
--       WHERE b.employee_id = 'B-' || split_part(a.employee_id,'-',3)
--       AND b.id <> a.id
--     );
DO $$
DECLARE
  rec RECORD;
  v_desired TEXT;
  v_new_id  TEXT;
BEGIN
  FOR rec IN
    SELECT id, employee_id
    FROM public.agents
    WHERE employee_id LIKE 'BZ-EMP-%'
    ORDER BY employee_id
  LOOP
    v_desired := 'B-' || split_part(rec.employee_id, '-', 3);

    -- Check whether the desired B-<n> value is already taken by another row
    IF EXISTS (
      SELECT 1 FROM public.agents
      WHERE employee_id = v_desired
        AND id <> rec.id
    ) THEN
      -- Conflict: assign a fresh ID from the sequence
      v_new_id := 'B-' || nextval('public.agent_emp_seq')::text;
    ELSE
      v_new_id := v_desired;
    END IF;

    UPDATE public.agents SET employee_id = v_new_id WHERE id = rec.id;
  END LOOP;
END $$;

-- Post-migration verification (run after to confirm no duplicates remain):
--   SELECT employee_id, COUNT(*) FROM public.agents GROUP BY employee_id HAVING COUNT(*) > 1;

-- Step 4: Verification query — check all current employee IDs
-- SELECT id, full_name, employee_id FROM public.agents ORDER BY employee_id;

-- ============================================================
-- NEXT ID QUERY: run this any time to see what the next ID will be
-- ============================================================
-- SELECT 'B-' || (last_value + 1)::text AS next_employee_id
-- FROM public.agent_emp_seq;

-- ============================================================
-- USEFUL COLUMN REFERENCE for agents table
-- ============================================================
-- Column: employee_id  TEXT NOT NULL UNIQUE
-- Auto-generated by trigger `agents_set_ids` (before insert)
-- Format after this migration: B-{number}  e.g. B-3231
-- To manually assign an ID on insert: set employee_id in your INSERT statement
-- To get the next auto-assigned ID preview:
--   SELECT 'B-' || (last_value + 1)::text FROM public.agent_emp_seq;
